# Header
menu:
  主页: /
#  小技术: /categories/coding/
#  小清新: /categories/life/
  文章: /archives
  关于: /about
rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
twitter: lwt1367
google_plus: '115031676619400074158'
fb_admins: lwt1367
fb_app_id:

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true
# Scroll to top
go_top: true
# widget-archive
show_count: true
duoshuo_shortname: TaoSama

# Sidebar
sidebar: left
widgets:
- about_me
- recommend_posts
- links
- category
- archive
- recent_comments
# - weibo
# - recent_posts
# - tagcloud

# about me
about_me:
  avatar: /css/images/avatar.png
  texts:
  - <a href="/about/" style="color:orange">老顽童</a>
  - <a href="http://codeforces.com/profile/TaoSama" style="color:purple">TaoSama</a>
  - 迷茫的搬砖工 / 永不退役的ACMer

recommend_posts:
  常见错误小结: /2016/05/02/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF%E5%B0%8F%E7%BB%93/
  Hello World —— 博客搭建历程: /2016/03/09/Hello%20World%20%E2%80%94%E2%80%94%20%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E5%8E%86%E7%A8%8B/
  
  
# Links
links:
  我的CSDN: http://blog.csdn.net/lwt36/
  我的知乎: http://www.zhihu.com/people/ye-zhu-shui-han/
  果姐姐: http://notdeep.github.io/
  WMW: https://cloverii.github.io/
  Mathon: http://blog.luoxinchen.me/
  forever97: http://www.cnblogs.com/forever97/
  liziy: http://liziyang96.com/
  liuyuhong: http://blog.csdn.net/viphong
  QAQ: http://blog.csdn.net/a1s4z5/
  qwb: http://blog.csdn.net/qwb492859377

